const FakeUsers = [

    {
        id: 'a1b2c3d4e5f6',
        name: 'Omar Khaled',
        email: 'omar.khaled@fakeemail.com',
        phone: '01140067845',
        role: 'admin',
    },
    {
        id: 'g7h8i9j0k1l2',
        name: 'Mohamed Hisham',
        email: 'mohamed.hisham@fakeemail.com',
        phone: '01108954712',
        role: 'admin',
    },
    {
        id: 'm3n4o5p6q7r8',
        name: 'Mahmoud Hisham',
        email: 'mahmoud.hisham@fakeemail.com',
        phone: '01234567890',
        role: 'admin',
    },
    {
        id: 's9t0u1v2w3x4',
        name: 'Ahmed Hisham',
        email: 'ahmed.hisham@fakeemail.com',
        phone: '01123456789',
        role: 'admin',
    },
    {
        id: 'y5z6a7b8c9d0',
        name: 'Sara Mohamed',
        email: 'sara.mohamed@fakeemail.com',
        phone: '01567891234',
        role: 'user',
    },
    {
        id: 'e1f2g3h4i5j6',
        name: 'Youssef Ali',
        email: 'youssef.ali@fakeemail.com',
        phone: '01098765432',
        role: 'admin',
    },
    {
        id: 'k7l8m9n0o1p2',
        name: 'Fatma Hassan',
        email: 'fatma.hassan@fakeemail.com',
        phone: '01112345678',
        role: 'user',
    },
    {
        id: 'q3r4s5t6u7v8',
        name: 'Khaled Nabil',
        email: 'khaled.nabil@fakeemail.com',
        phone: '01234567891',
        role: 'admin',
    },
    {
        id: 'w9x0y1z2a3b4',
        name: 'Nour El-Din',
        email: 'nour.eldin@fakeemail.com',
        phone: '01512345678',
        role: 'user',
    },
    {
        id: 'c5d6e7f8g9h0',
        name: 'Mona Salah',
        email: 'mona.salah@fakeemail.com',
        phone: '01156789123',
        role: 'user',
    },
    {
        id: 'i1j2k3l4m5n6',
        name: 'Amr Tarek',
        email: 'amr.tarek@fakeemail.com',
        phone: '01045678912',
        role: 'admin',
    },
    {
        id: 'o7p8q9r0s1t2',
        name: 'Hassan Youssef',
        email: 'hassan.youssef@fakeemail.com',
        phone: '01267894567',
        role: 'user',
    },
    {
        id: 'u3v4w5x6y7z8',
        name: 'Aya Hossam',
        email: 'aya.hossam@fakeemail.com',
        phone: '01123456790',
        role: 'admin',
    },
    {
        id: 'a9b0c1d2e3f4',
        name: 'Rana Samir',
        email: 'rana.samir@fakeemail.com',
        phone: '01598765432',
        role: 'user',
    },
    {
        id: 'g5h6i7j8k9l0',
        name: 'Mahmoud Adel',
        email: 'mahmoud.adel@fakeemail.com',
        phone: '01087654321',
        role: 'admin',
    },
    {
        id: 'm1n2o3p4q5r6',
        name: 'Nadine Sherif',
        email: 'nadine.sherif@fakeemail.com',
        phone: '01234567898',
        role: 'user',
    },
    {
        id: 's7t8u9v0w1x2',
        name: 'Tamer Khalil',
        email: 'tamer.khalil@fakeemail.com',
        phone: '01167893456',
        role: 'admin',
    },
    {
        id: 'y3z4a5b6c7d8',
        name: 'Laila Nabil',
        email: 'laila.nabil@fakeemail.com',
        phone: '01523467890',
        role: 'user',
    },
    {
        id: 'e9f0g1h2i3j4',
        name: 'Mostafa Kamel',
        email: 'mostafa.kamel@fakeemail.com',
        phone: '01098764532',
        role: 'admin',
    },
    {
        id: 'k5l6m7n8o9p0',
        name: 'Rania Ahmed',
        email: 'rania.ahmed@fakeemail.com',
        phone: '01236789045',
        role: 'user',
    },
    {
        id: 'q1r2s3t4u5v6',
        name: 'Karim Fathy',
        email: 'karim.fathy@fakeemail.com',
        phone: '01134567890',
        role: 'admin',
    }

];

export default FakeUsers;
